# Generated by Django 5.2.1 on 2025-06-06 01:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id_mantenimiento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_programada', models.DateField()),
                ('fecha_finalizado', models.DateField(blank=True, null=True)),
                ('tipo_mantenimiento', models.CharField(choices=[('PREVENTIVO', 'PREVENTIVO'), ('CORRECTIVO', 'CORRECTIVO'), ('PREDICTIVO', 'PREDICTIVO')], max_length=10)),
                ('estado', models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('FINALIZADO', 'FINALIZADO'), ('PENDIENTE', 'PENDIENTE'), ('CANCELADO', 'CANCELADO')], default='ACTIVO', max_length=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
                'db_table': 'mantenimiento',
            },
        ),
        migrations.CreateModel(
            name='MotivoMantenimiento',
            fields=[
                ('id_motivo', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Motivo Mantenimiento',
                'verbose_name_plural': 'Motivos Mantenimiento',
                'db_table': 'motivo_mantenimiento',
            },
        ),
        migrations.CreateModel(
            name='NotificacionGlobal',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(choices=[('DOCUMENTO_CHOFER', 'Documento Chofer'), ('DOCUMENTO_VEHICULOS', 'Documento Vehiculos'), ('MANTENIMIENTO', 'Mantenimiento Vehículo'), ('DETALLE_MANTENIMIENTO', 'Detalle de Mantenimiento'), ('MOTIVO_MANTENIMIENTO', 'Motivo de Mantenimiento'), ('VEHICULO', 'Vehículo'), ('USUARIO', 'Usuario'), ('GENERAL', 'General')], default='INFO', max_length=25)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('rol_destino', models.CharField(blank=True, help_text='Si se asigna, la notificación será para todos los usuarios de este rol', max_length=1, null=True)),
            ],
            options={
                'verbose_name': 'Notificación Global',
                'verbose_name_plural': 'Notificaciones Globales',
                'db_table': 'notificacion_global',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id_vehiculo', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Vehiculo')),
                ('placa', models.CharField(max_length=20, unique=True, verbose_name='Placa Vehiculo')),
                ('kilometraje', models.IntegerField(verbose_name='Kilometraje Vehiculo')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('EN_MANTENIMIENTO', 'En Mantenimiento')], default='ACTIVO', max_length=16, verbose_name='Estado del vehículo')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca vehículo')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo vehículo')),
                ('motor', models.CharField(blank=True, max_length=50, verbose_name='Número/Código del motor')),
                ('anio', models.IntegerField(blank=True, verbose_name='Año de fabricación')),
                ('color', models.CharField(blank=True, max_length=30, verbose_name='Color del vehículo')),
                ('tipologia', models.CharField(blank=True, max_length=50, verbose_name='Tipología del vehículo')),
                ('capacidad_carga', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Capacidad máxima de carga (kg)')),
                ('capacidad_combustible', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Capacidad del tanque (litros')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo del vehículo')),
                ('tipo_combustible', models.CharField(choices=[('GASOLINA', 'Gasolina'), ('DIESEL', 'Diésel')], default='GASOLINA', max_length=10, verbose_name='Tipo de Combustible')),
                ('fecha_creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Vehiculo',
                'verbose_name_plural': 'Vehiculos',
                'db_table': 'vehiculo',
            },
        ),
        migrations.CreateModel(
            name='DetalleMantenimiento',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.CharField(max_length=60)),
                ('cantidad', models.IntegerField()),
                ('precio_und', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_mantenimiento', models.ForeignKey(db_column='id_mantenimiento', on_delete=django.db.models.deletion.RESTRICT, to='WSI_API.mantenimiento')),
            ],
            options={
                'verbose_name': 'Detalle Mantenimiento',
                'verbose_name_plural': 'Detalles Mantenimiento',
                'db_table': 'detalle_mantenimiento',
            },
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='id_motivo',
            field=models.ForeignKey(blank=True, db_column='id_motivo', on_delete=django.db.models.deletion.RESTRICT, to='WSI_API.motivomantenimiento'),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='id_vehiculo',
            field=models.ForeignKey(db_column='id_vehiculo', on_delete=django.db.models.deletion.RESTRICT, to='WSI_API.vehiculo'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=150, unique=True, verbose_name='correo electrónico')),
                ('nombre', models.CharField(max_length=30, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=30, verbose_name='apellido')),
                ('tipoCedula', models.CharField(max_length=1, verbose_name='tipo de cédula')),
                ('cedula', models.CharField(max_length=8, unique=True, verbose_name='cédula')),
                ('telefono', models.CharField(max_length=10, verbose_name='teléfono')),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True, verbose_name='fecha de registro')),
                ('rol', models.CharField(max_length=1, verbose_name='rol')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='es personal')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='es superusuario')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='id_mecanico',
            field=models.ForeignKey(blank=True, db_column='id_usuario', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DocumentoChofer',
            fields=[
                ('id_documento_chofer', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(choices=[('CEDULA_IDENTIDAD', 'Cédula de Identidad'), ('LICENCIA_CONDUCIR', 'Licencia de Conducir'), ('CARTA_MEDICA', 'Carta Médica')], max_length=30)),
                ('numero_documento', models.CharField(max_length=50)),
                ('fecha_emision', models.DateField()),
                ('fecha_caducidad', models.DateField()),
                ('archivo', models.FileField(upload_to='documentos_choferes/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('chofer', models.ForeignKey(limit_choices_to={'rol': '2'}, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificacionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leida', models.BooleanField(default=False)),
                ('fecha_leida', models.DateTimeField(blank=True, null=True)),
                ('notificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='WSI_API.notificacionglobal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación Usuario',
                'verbose_name_plural': 'Notificaciones Usuario',
                'db_table': 'notificacion_usuario',
                'unique_together': {('notificacion', 'usuario')},
            },
        ),
    ]
