# Generated by Django 5.2.1 on 2025-05-18 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id_vehiculo', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Vehiculo')),
                ('placa', models.CharField(max_length=20, unique=True, verbose_name='Placa Vehiculo')),
                ('kilometraje', models.IntegerField(verbose_name='Kilometraje Vehiculo')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('EN_MANTENIMIENTO', 'En Mantenimiento')], default='ACTIVO', max_length=16, verbose_name='Estado del vehículo')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca vehículo')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo vehículo')),
                ('motor', models.CharField(blank=True, max_length=50, verbose_name='Número/Código del motor')),
                ('anio', models.IntegerField(blank=True, verbose_name='Año de fabricación')),
                ('color', models.CharField(blank=True, max_length=30, verbose_name='Color del vehículo')),
                ('tipologia', models.CharField(blank=True, max_length=50, verbose_name='Tipología del vehículo')),
                ('capacidad_carga', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Capacidad máxima de carga (kg)')),
                ('capacidad_combustible', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Capacidad del tanque (litros')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo del vehículo')),
                ('tipo_combustible', models.CharField(choices=[('GASOLINA', 'Gasolina'), ('DIESEL', 'Diésel'), ('ELECTRICO', 'Eléctrico'), ('HIBRIDO', 'Híbrido'), ('GAS', 'Gas'), ('OTRO', 'Otro')], default='GASOLINA', max_length=10, verbose_name='Tipo de Combustible')),
                ('fecha_creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Vehiculo',
                'verbose_name_plural': 'Vehiculos',
                'db_table': 'vehiculo',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=150, unique=True, verbose_name='correo electrónico')),
                ('nombre', models.CharField(max_length=30, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=30, verbose_name='apellido')),
                ('tipoCedula', models.CharField(max_length=1, verbose_name='tipo de cédula')),
                ('cedula', models.CharField(max_length=8, unique=True, verbose_name='cédula')),
                ('telefono', models.CharField(max_length=10, verbose_name='teléfono')),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True, verbose_name='fecha de registro')),
                ('rol', models.CharField(max_length=1, verbose_name='rol')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='es personal')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='es superusuario')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
