# Generated by Django 5.2.1 on 2025-06-06 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WSI_API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(max_length=11, verbose_name='teléfono'),
        ),
    ]
