# Generated by Django 5.2.1 on 2025-05-18 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WSI_API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo_combustible',
            field=models.CharField(choices=[('GASOLINA', 'Gasolina'), ('DIESEL', 'Diésel')], default='GASOLINA', max_length=10, verbose_name='Tipo de Combustible'),
        ),
    ]
