# Generated by Django 5.2.1 on 2025-05-21 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WSI_API', '0002_alter_vehiculo_tipo_combustible'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoMantenimiento',
            fields=[
                ('id_motivo', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Motivo Mantenimiento',
                'verbose_name_plural': 'Motivos Mantenimiento',
                'db_table': 'motivo_mantenimiento',
            },
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id_mantenimiento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_programada', models.DateField()),
                ('fecha_finalizado', models.DateField(blank=True, null=True)),
                ('tipo_mantenimiento', models.CharField(choices=[('PREVENTIVO', 'PREVENTIVO'), ('CORRECTIVO', 'CORRECTIVO'), ('PREDICTIVO', 'PREDICTIVO')], max_length=10)),
                ('estado', models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('FINALIZADO', 'FINALIZADO'), ('PENDIENTE', 'PENDIENTE'), ('CANCELADO', 'CANCELADO')], default='ACTIVO', max_length=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('id_mecanico', models.ForeignKey(blank=True, db_column='id_usuario', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('id_vehiculo', models.ForeignKey(db_column='id_vehiculo', on_delete=django.db.models.deletion.RESTRICT, to='WSI_API.vehiculo')),
                ('id_motivo', models.ForeignKey(blank=True, db_column='id_motivo', on_delete=django.db.models.deletion.RESTRICT, to='WSI_API.motivomantenimiento')),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
                'db_table': 'mantenimiento',
            },
        ),
        migrations.CreateModel(
            name='DetalleMantenimiento',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.CharField(max_length=60)),
                ('cantidad', models.IntegerField()),
                ('precio_und', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_mantenimiento', models.ForeignKey(db_column='id_mantenimiento', on_delete=django.db.models.deletion.RESTRICT, to='WSI_API.mantenimiento')),
            ],
            options={
                'verbose_name': 'Detalle Mantenimiento',
                'verbose_name_plural': 'Detalles Mantenimiento',
                'db_table': 'detalle_mantenimiento',
            },
        ),
    ]
