# Generated by Django 5.2.1 on 2025-05-27 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WSI_API', '0003_motivomantenimiento_mantenimiento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoChofer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('CEDULA_IDENTIDAD', 'Cédula de Identidad'), ('LICENCIA_CONDUCIR', 'Licencia de Conducir'), ('CARTA_MEDICA', 'Carta Médica')], max_length=30)),
                ('numero_documento', models.CharField(max_length=50)),
                ('fecha_emision', models.DateField()),
                ('fecha_caducidad', models.DateField()),
                ('archivo', models.FileField(upload_to='documentos_choferes/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('chofer', models.ForeignKey(limit_choices_to={'rol': '2'}, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
