# Generated by Django 5.2.1 on 2025-06-08 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WSI_API', '0003_motivos'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='borrado',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Borrado'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='motivo_borrado',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de borrado'),
        ),
    ]
