# Generated by Django 5.2.1 on 2025-05-27 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WSI_API', '0004_documentochofer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentochofer',
            old_name='chofer',
            new_name='id_chofer',
        ),
        migrations.RemoveField(
            model_name='documentochofer',
            name='id',
        ),
        migrations.AddField(
            model_name='documentochofer',
            name='id_documento_chofer',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
