# Generated by Django 5.2.1 on 2025-06-08 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WSI_API', '0004_vehiculo_borrado_vehiculo_motivo_borrado'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoVehiculo',
            fields=[
                ('id_documento_vehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(choices=[('RCV', 'RCV'), ('TRIMESTRES', 'Trimestres')], max_length=30)),
                ('numero_documento', models.CharField(max_length=50)),
                ('fecha_emision', models.DateField()),
                ('fecha_caducidad', models.DateField()),
                ('archivo', models.FileField(upload_to='documentos_choferes/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('Vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='WSI_API.vehiculo')),
            ],
        ),
    ]
