# Generated by Django 5.2.1 on 2025-05-27 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WSI_API', '0005_rename_chofer_documentochofer_id_chofer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentochofer',
            old_name='id_chofer',
            new_name='chofer',
        ),
    ]
