# Generated by Django 5.2.1 on 2025-06-12 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WSI_API', '0005_documentovehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='fecha_terminado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentovehiculo',
            name='archivo',
            field=models.FileField(upload_to='documentos_vehiculos/'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='placa',
            field=models.CharField(error_messages={'unique': 'Ya existe un vehículo registrado con esta placa.'}, max_length=20, unique=True, verbose_name='Placa Vehiculo'),
        ),
    ]
