# Generated by Django 5.2.1 on 2025-06-05 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WSI_API', '0006_rename_id_chofer_documentochofer_chofer'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionGlobal',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(choices=[('INFO', 'Información'), ('ALERTA', 'Alerta'), ('SISTEMA', 'Sistema')], default='INFO', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('rol_destino', models.CharField(blank=True, help_text='Si se asigna, la notificación será para todos los usuarios de este rol', max_length=1, null=True)),
            ],
            options={
                'verbose_name': 'Notificación Global',
                'verbose_name_plural': 'Notificaciones Globales',
                'db_table': 'notificacion_global',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='NotificacionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leida', models.BooleanField(default=False)),
                ('fecha_leida', models.DateTimeField(blank=True, null=True)),
                ('notificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='WSI_API.notificacionglobal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación Usuario',
                'verbose_name_plural': 'Notificaciones Usuario',
                'db_table': 'notificacion_usuario',
                'unique_together': {('notificacion', 'usuario')},
            },
        ),
    ]
