# Generated by Django 5.2.1 on 2025-06-14 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WSI_API', '0006_mantenimiento_fecha_terminado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteFalla',
            fields=[
                ('id_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('motivo_falla', models.CharField(max_length=60, verbose_name='Mmotivo_de_falla')),
                ('fecha_reporte', models.DateField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Operativo', 'Operativo'), ('No Operativo', 'No Operativo')], default='Operativo', max_length=15)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('id_vehiculo', models.ForeignKey(db_column='id_vehiculo', on_delete=django.db.models.deletion.RESTRICT, to='WSI_API.vehiculo')),
            ],
            options={
                'verbose_name': 'Reporte de Falla',
                'verbose_name_plural': 'Reportes de Fallas',
                'db_table': 'reportes_falla',
            },
        ),
    ]
