# Generated by Django 5.2.1 on 2025-06-18 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WSI_API', '0007_reportefalla'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportefalla',
            name='eliminada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reportefalla',
            name='revisada',
            field=models.BooleanField(default=False),
        ),
    ]
