# Generated by Django 5.2.1 on 2025-06-30 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WSI_API', '0008_reportefalla_eliminada_reportefalla_revisada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportefalla',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
