# Generated by Django 5.2.1 on 2025-07-19 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WSI_API', '0009_alter_reportefalla_id_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='reset_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
