# Generated by Django 5.2.1 on 2025-07-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WSI_API', '0010_usuario_reset_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='borrado',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Borrado'),
        ),
    ]
