# Generated by Django 5.2.1 on 2025-07-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WSI_API', '0011_usuario_borrado'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='borrado',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Borrado'),
        ),
    ]
